name: PowerShell script
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  projectsJson:
    description: JSON formatted string of projects to build
    required: true
  buildOrderJson:
    description: JSON formatted build order
    required: true
  buildOrderDepth:
    description: Build order depth
    required: true
  workflowDepth:
    description: Workflow depth
    required: true
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      env:
        _projectsJson: ${{ inputs.projectsJson }}
        _buildOrderJson: ${{ inputs.buildOrderJson }}
        _buildOrderDepth: ${{ inputs.buildOrderDepth }}
        _workflowDepth: ${{ inputs.workflowDepth }}
      run: try { ${{ github.action_path }}/DetermineBuildOrder.ps1 -projectsJson $ENV:_projectsJson -buildOrderJson $ENV:_buildOrderJson -buildOrderDepth $ENV:_BuildOrderDepth -workflowDepth $ENV:_WorkflowDepth } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("*",'').Replace("*",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
