name: 'Pull Request Build'

on:
  pull_request_target:
    paths-ignore:
      - '**.md'
    branches: [ 'main' ]

defaults:
  run:
    shell: powershell

permissions:
  contents: read
  actions: read
  pull-requests: read

jobs:
  PregateCheck:
    runs-on: [ windows-latest ]
    steps:
      - uses: aholstrup1/AL-Go-Actions/VerifyPRChanges@main
        with:
          baseSHA: ${{ github.event.pull_request.base.sha }}
          headSHA: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

  Initialization:
    needs: [ PregateCheck ]
    runs-on: [ windows-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
      settings: ${{ steps.ReadSettings.outputs.SettingsJson }}
      projects: ${{ steps.ReadSettings.outputs.ProjectsJson }}
      projectCount: ${{ steps.ReadSettings.outputs.ProjectCount }}
      environments: ${{ steps.ReadSettings.outputs.EnvironmentsJson }}
      environmentCount: ${{ steps.ReadSettings.outputs.EnvironmentCount }}
      githubRunner: ${{ steps.ReadSettings.outputs.GitHubRunnerJson }}
      githubRunnerShell: ${{ steps.ReadSettings.outputs.GitHubRunnerShell }}
      checkRunId: ${{ steps.CreateCheckRun.outputs.checkRunId }}
      projectDependenciesJson: ${{ steps.ReadSettings.outputs.ProjectDependenciesJson }}
      buildOrderJson: ${{ steps.ReadSettings.outputs.BuildOrderJson }}
      buildOrderDepth: ${{ steps.ReadSettings.outputs.BuildOrderDepth }}
      buildModes: ${{ steps.ReadSettings.outputs.BuildModes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Initialize the workflow
        id: init
        uses: aholstrup1/AL-Go-Actions/WorkflowInitialize@main
        with:
          shell: powershell
          eventId: "DO0091"

      - name: Read settings
        id: ReadSettings
        uses: aholstrup1/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          getProjects: 'Y'
          getEnvironments: '*'
      
      - name: Determine Build Order
        if: env.workflowDepth > 1
        id: BuildOrder
        uses: aholstrup1/AL-Go-Actions/DetermineBuildOrder@main
        with:
          projects: ${{ steps.ReadSettings.outputs.ProjectsJson }}
          buildOrder: ${{ steps.ReadSettings.outputs.BuildOrderJson }}
          buildOrderDepth: ${{ steps.ReadSettings.outputs.BuildOrderDepth }}
          workflowDepth: ${{ env.workflowDepth }}
          outputPath: ${{ env.GITHUB_OUTPUT }}

  Build:
    needs: [ Initialization ]
    if: ${{ needs.Initialization.outputs.projectCount > 0 }}
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    defaults:
      run:
        shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
    strategy:
      matrix:
        project: ${{ fromJson(needs.Initialization.outputs.projects) }}
        buildMode: ${{ fromJson(needs.Initialization.outputs.buildModes) }}
      fail-fast: false
    name: Build ${{ matrix.project }} - ${{ matrix.buildMode }}
    outputs:
      AppsArtifactsName: ${{ steps.calculateArtifactNames.outputs.AppsArtifactsName }}
      TestAppsArtifactsName: ${{ steps.calculateArtifactNames.outputs.TestAppsArtifactsName }}
      TestResultsArtifactsName: ${{ steps.calculateArtifactNames.outputs.TestResultsArtifactsName }}
      BcptTestResultsArtifactsName: ${{ steps.calculateArtifactNames.outputs.BcptTestResultsArtifactsName }}
      BuildOutputArtifactsName: ${{ steps.calculateArtifactNames.outputs.BuildOutputArtifactsName }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
    
      - name: Download thisbuild artifacts
        if: env.workflowDepth > 1
        uses: actions/download-artifact@v3
        with:
          path: '.dependencies'

      - name: Read settings
        uses: aholstrup1/AL-Go-Actions/ReadSettings@main
        with:
          shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          project: ${{ matrix.project }}

      - name: Read secrets
        uses: aholstrup1/AL-Go-Actions/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'licenseFileUrl,insiderSasToken,keyVaultCertificateUrl,keyVaultCertificatePassword,keyVaultClientId' #TODO: Update list of secrets to only fetch the needed ones 

      - name: Run pipeline
        id: RunPipeline
        uses: aholstrup1/AL-Go-Actions/RunPipeline@main
        env:
          BuildMode: ${{ matrix.buildMode }}
        with:
          shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          Project: ${{ matrix.project }}
          ProjectDependenciesJson: ${{ needs.Initialization.outputs.projectDependenciesJson }}
          settingsJson: ${{ env.Settings }}
          SecretsJson: ${{ env.RepoSecrets }}
          buildMode: ${{ matrix.buildMode }}

      - name: Calculate Artifact names
        uses: aholstrup1/AL-Go-Actions/CalculateArtifactNames@main
        if: success() || failure()
        with:
          shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
          settingsJson: ${{ env.Settings }}
          project: ${{ matrix.project }}
          buildMode: ${{ matrix.buildMode }}
          refName: ${{ github.ref_name }}

      - name: Upload thisbuild artifacts - apps
        if: env.workflowDepth > 1
        uses: actions/upload-artifact@v3
        with:
          name: 'thisbuild-${{ matrix.project }}-${{ env.BuildMode }}Apps'
          path: '${{ matrix.project }}/.buildartifacts/Apps/'
          if-no-files-found: ignore
          retention-days: 1

      - name: Upload thisbuild artifacts - test apps
        if: env.workflowDepth > 1
        uses: actions/upload-artifact@v3
        with:
          name: 'thisbuild-${{ matrix.project }}-${{ env.BuildMode }}TestApps'
          path: '${{ matrix.project }}/.buildartifacts/TestApps/'
          if-no-files-found: ignore
          retention-days: 1

      - name: Publish artifacts - apps
        uses: actions/upload-artifact@v3
        if: github.ref_name == 'main' || startswith(github.ref_name, 'release/') || needs.Initialization.outputs.environmentCount > 0
        with:
          name: ${{ env.AppsArtifactsName }}
          path: '${{ matrix.project }}/.buildartifacts/Apps/'
          if-no-files-found: ignore

      - name: Publish artifacts - dependencies
        uses: actions/upload-artifact@v3
        if: github.ref_name == 'main' || startswith(github.ref_name, 'release/') || needs.Initialization.outputs.environmentCount > 0
        with:
          name: ${{ env.DependenciesArtifactsName }}
          path: '${{ matrix.project }}/.buildartifacts/Dependencies/'
          if-no-files-found: ignore

      - name: Publish artifacts - test apps
        uses: actions/upload-artifact@v3
        if: github.ref_name == 'main' || startswith(github.ref_name, 'release/') || needs.Initialization.outputs.environmentCount > 0
        with:
          name: ${{ env.TestAppsArtifactsName }}
          path: '${{ matrix.project }}/.buildartifacts/TestApps/'
          if-no-files-found: ignore

      - name: Publish artifacts - build output
        uses: actions/upload-artifact@v3
        if: (success() || failure()) && (hashFiles(format('{0}/BuildOutput.txt',matrix.project)) != '')
        with:
          name: ${{ env.BuildOutputArtifactsName }}
          path: '${{ matrix.project }}/BuildOutput.txt'
          if-no-files-found: ignore

      - name: Publish artifacts - container event log
        uses: actions/upload-artifact@v3
        if: (failure()) && (hashFiles(format('{0}/ContainerEventLog.evtx',matrix.project)) != '')
        with:
          name: ${{ env.ContainerEventLogArtifactsName }}
          path: '${{ matrix.project }}/ContainerEventLog.evtx'
          if-no-files-found: ignore

      - name: Publish artifacts - test results
        uses: actions/upload-artifact@v3
        if: (success() || failure()) && (hashFiles(format('{0}/TestResults.xml',matrix.project)) != '')
        with:
          name: ${{ env.TestResultsArtifactsName }}
          path: '${{ matrix.project }}/TestResults.xml'
          if-no-files-found: ignore

      - name: Publish artifacts - bcpt test results
        uses: actions/upload-artifact@v3
        if: (success() || failure()) && (hashFiles(format('{0}/bcptTestResults.json',matrix.project)) != '')
        with:
          name: ${{ env.BcptTestResultsArtifactsName }}
          path: '${{ matrix.project }}/bcptTestResults.json'
          if-no-files-found: ignore

      - name: Analyze Test Results
        id: analyzeTestResults
        if: success() || failure()
        uses: aholstrup1/AL-Go-Actions/AnalyzeTests@main
        with:
          shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          Project: ${{ matrix.project }}

      - name: Cleanup
        if: always()
        uses: aholstrup1/AL-Go-Actions/PipelineCleanup@main
        with:
          shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          Project: ${{ matrix.project }}

  PostProcess:
    runs-on: [ windows-latest ]
    needs: [ Initialization, Build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Finalize the workflow
        id: PostProcess
        uses: aholstrup1/AL-Go-Actions/WorkflowPostProcess@main
        with:
          shell: powershell
          eventId: "DO0091"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}